# Generated by Django 5.0 on 2024-01-11 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='dateAndTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
