# Generated by Django 5.0 on 2024-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
    ]
